spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: postgres
    password: 15975300
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    baseline-one-migrate: true
    enabled: true
    baseline-description: "init"
    baseline-version: 0
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  application:
    name: product-service

server:
  port: 8050